import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  ResponsiveContainer,
  Tooltip,
  ReferenceLine,
} from "recharts";
import { useSensors } from "../../hooks/useSensors";

const ZONES = [
  {
    id: "loading-temp",
    name: "Loading Bay",
    color: "#f59e0b",
    target: { min: 15, max: 25 },
  },
  {
    id: "cold-a-temp",
    name: "Cold Room A (Fresh)",
    color: "#0ea5e9",
    target: { min: 2, max: 4 },
  },
  {
    id: "cold-b-temp",
    name: "Cold Room B (Freezer)",
    color: "#3b82f6",
    target: { min: -20, max: -16 },
  },
  {
    id: "dry-temp",
    name: "Dry Storage",
    color: "#f97316",
    target: { min: 15, max: 20 },
  },
];

// Zone data from agent-generated visualization
interface ZoneData {
  id: string;
  name: string;
  currentTemp: number | null;
  targetMin: number;
  targetMax: number;
  status: string;
}

interface ZoneHealthData {
  zones?: ZoneData[];
}

interface ZoneHealthVisualizationProps {
  data?: ZoneHealthData;
}

// Color mapping for zone IDs
const ZONE_COLORS: Record<string, string> = {
  Z1: "#f59e0b",
  Z2: "#0ea5e9",
  Z3: "#3b82f6",
  Z4: "#f97316",
};

export function ZoneHealthVisualization({
  data,
}: ZoneHealthVisualizationProps) {
  const { data: sensors, isLoading } = useSensors();

  // If agent-provided data exists, render it
  if (data?.zones && data.zones.length > 0) {
    return (
      <div className="mx-auto max-w-5xl space-y-6">
        <div>
          <h1 className="text-xl font-semibold text-text-primary">
            Zone Health Overview
          </h1>
          <p className="text-sm text-text-muted">
            Current temperatures across all facility zones
          </p>
        </div>

        {/* Summary Cards from agent data */}
        <div className="grid grid-cols-4 gap-4">
          {data.zones.map((zone) => {
            const currentTemp = zone.currentTemp;
            const color = ZONE_COLORS[zone.id] || "#64748b";

            return (
              <div
                key={zone.id}
                className="rounded-lg border border-border-subtle bg-bg-surface p-4"
              >
                <div className="mb-2 flex items-center justify-between">
                  <span
                    className="h-2 w-2 rounded-full"
                    style={{ backgroundColor: color }}
                  />
                  <span
                    className={`text-xs font-medium ${
                      zone.status === "normal"
                        ? "text-emerald-400"
                        : "text-amber-400"
                    }`}
                  >
                    {zone.status === "normal" ? "In Range" : zone.status}
                  </span>
                </div>
                <div className="text-2xl font-bold text-text-primary">
                  {currentTemp !== null ? `${currentTemp.toFixed(1)}°C` : "N/A"}
                </div>
                <div className="text-xs text-text-muted">{zone.name}</div>
                <div className="mt-1 text-[10px] text-text-muted">
                  Target: {zone.targetMin}°C to {zone.targetMax}°C
                </div>
              </div>
            );
          })}
        </div>

        <div className="text-center text-xs text-text-muted">
          Generated by AI agent • {new Date().toLocaleTimeString()}
        </div>
      </div>
    );
  }

  // Fall back to sensor-based rendering
  if (isLoading || !sensors) {
    return (
      <div className="flex h-64 items-center justify-center text-text-muted">
        Loading sensor data...
      </div>
    );
  }

  const tempSensors = sensors.filter((s) => s.sensorType === "environmental");

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-text-primary">
          Zone Health Overview
        </h1>
        <p className="text-sm text-text-muted">
          24-hour temperature trends across all facility zones
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-4 gap-4">
        {ZONES.map((zone) => {
          const sensor = tempSensors.find((s) => s.id === zone.id);
          if (!sensor) return null;

          const currentTemp = parseFloat(
            sensor.reading.value.replace(/[°C]/g, ""),
          );
          const isInRange =
            currentTemp >= zone.target.min && currentTemp <= zone.target.max;

          return (
            <div
              key={zone.id}
              className="rounded-lg border border-border-subtle bg-bg-surface p-4"
            >
              <div className="mb-2 flex items-center justify-between">
                <span
                  className="h-2 w-2 rounded-full"
                  style={{ backgroundColor: zone.color }}
                />
                <span
                  className={`text-xs font-medium ${isInRange ? "text-emerald-400" : "text-amber-400"}`}
                >
                  {isInRange ? "In Range" : "Warning"}
                </span>
              </div>
              <div className="text-2xl font-bold text-text-primary">
                {sensor.reading.value}
              </div>
              <div className="text-xs text-text-muted">{zone.name}</div>
              <div className="mt-1 text-[10px] text-text-muted">
                Target: {zone.target.min}°C to {zone.target.max}°C
              </div>
            </div>
          );
        })}
      </div>

      {/* Charts */}
      <div className="grid grid-cols-2 gap-6">
        {ZONES.map((zone) => {
          const sensor = tempSensors.find((s) => s.id === zone.id);
          if (!sensor) return null;

          const chartData = sensor.trend.map((value, i) => ({
            hour: `${i}:00`,
            temp: value,
          }));

          return (
            <div
              key={zone.id}
              className="rounded-lg border border-border-subtle bg-bg-surface p-4"
            >
              <div className="mb-3 flex items-center gap-2">
                <span
                  className="h-3 w-3 rounded-full"
                  style={{ backgroundColor: zone.color }}
                />
                <span className="font-medium text-text-primary">
                  {zone.name}
                </span>
              </div>

              <div className="h-40">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart
                    data={chartData}
                    margin={{ top: 10, right: 10, bottom: 0, left: -20 }}
                  >
                    <defs>
                      <linearGradient
                        id={`gradient-${zone.id}`}
                        x1="0"
                        y1="0"
                        x2="0"
                        y2="1"
                      >
                        <stop
                          offset="0%"
                          stopColor={zone.color}
                          stopOpacity={0.3}
                        />
                        <stop
                          offset="100%"
                          stopColor={zone.color}
                          stopOpacity={0}
                        />
                      </linearGradient>
                    </defs>
                    <XAxis
                      dataKey="hour"
                      tick={{ fontSize: 10, fill: "var(--color-text-muted)" }}
                      tickLine={false}
                      axisLine={false}
                      interval={5}
                    />
                    <YAxis
                      tick={{ fontSize: 10, fill: "var(--color-text-muted)" }}
                      tickLine={false}
                      axisLine={false}
                      domain={["dataMin - 2", "dataMax + 2"]}
                    />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: "var(--color-bg-surface)",
                        border: "1px solid var(--color-border-subtle)",
                        borderRadius: "8px",
                        fontSize: "12px",
                      }}
                      labelStyle={{ color: "var(--color-text-muted)" }}
                    />
                    <ReferenceLine
                      y={zone.target.min}
                      stroke="var(--color-text-muted)"
                      strokeDasharray="3 3"
                      strokeOpacity={0.5}
                    />
                    <ReferenceLine
                      y={zone.target.max}
                      stroke="var(--color-text-muted)"
                      strokeDasharray="3 3"
                      strokeOpacity={0.5}
                    />
                    <Area
                      type="monotone"
                      dataKey="temp"
                      stroke={zone.color}
                      strokeWidth={2}
                      fill={`url(#gradient-${zone.id})`}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>

              <div className="mt-2 flex justify-between text-xs text-text-muted">
                <span>Min: {sensor.stats.min}°C</span>
                <span>Avg: {sensor.stats.avg}°C</span>
                <span>Max: {sensor.stats.max}°C</span>
              </div>
            </div>
          );
        })}
      </div>

      <div className="text-center text-xs text-text-muted">
        Data from the last 24 hours • Updated {new Date().toLocaleTimeString()}
      </div>
    </div>
  );
}
